language: go
go:
    - 1.9
    - 1.10

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
    - dep ensure
script:
    - test -z $(gofmt -s -l $GO_FILES)
    - make test
    - make build
    - go vet ./...
